agoat_deferredimages:
    path: /assets/images/g/{name}
    defaults:
        _scope: frontend
        _controller: "AgoatDeferredImagesBundle:DeferredImages:resize"
        name: default
    requirements:
        name: .*
    
