contao_imageondemand:
    path: /assets/images/g/{imgID}
    defaults:
        _scope: frontend
        _controller: "AgoatDeferredimagesBundle:Deferredimages:resize"
        imgID: default
    requirements:
        imgID: .*
    
