services:
    agoat.image.resizer:
        class: Agoat\DeferredImagesBundle\Image\DeferredResizer
        decorates: contao.image.resizer
        decoration_priority: 10
        public: false
        arguments:
            - "%contao.image.target_dir%"
            - "@contao.image.resize_calculator"
            - "@filesystem"
        calls:
            - ["setFramework", ["@contao.framework"]]

    contao.routing.image_loader:
        class: Agoat\DeferredImagesBundle\Routing\ImageControllerLoader
        public: false
        tags:
            - { name: routing.loader }